version = 1

[[annotations]]
path = ["test/**", "readme/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Alisa Lain <al1-ce@null.net>"
SPDX-License-Identifier = "OSL-3.0"

[[annotations]]
path = [".github/**", "dub.sdl", ".dub/**", ".gitignore", ".pre-commit-config.yaml", "dscanner.ini"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Alisa Lain <al1-ce@null.net>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [".todo.md", "AUTHORS.md", "CHANGEDLOG.md", "CONTRIBUTING.md", "README.md", "justfile", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Alisa Lain <al1-ce@null.net>"
SPDX-License-Identifier = "CC0-1.0"

